{
   "result" : [
      {
         "actionType" : "USER_FAILED_LOGIN",
         "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
         "namespace" : null,
         "workSourcePrincipal" : null,
         "startTime" : "2019-12-30T11:14:56.061Z",
         "workSourceName" : "admin",
         "user" : null,
         "parentAction" : null,
         "title" : "USER_FAILED_LOGIN",
         "failureMessageCode" : null,
         "endTime" : "2019-12-30T11:14:56.061Z",
         "workSource" : "SYSTEM",
         "type" : "Action",
         "reference" : "ACTION-55",
         "failureDescription" : null,
         "failureAction" : null,
         "details" : "Failed attempt to log in as user \"admin\" from IP \"172.16.124.26\".",
         "originIp" : "172.16.124.26",
         "state" : "FAILED",
         "report" : null
      },
      {
         "originIp" : "172.16.124.26",
         "details" : "Run SnapSync for database \"marina\".",
         "report" : null,
         "state" : "FAILED",
         "type" : "Action",
         "workSource" : "WEBSERVICE",
         "endTime" : "2019-12-30T11:14:32.445Z",
         "failureAction" : "Make sure that the username provided has access rights to system views, and that the host server can be reached.",
         "failureDescription" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n ",
         "reference" : "ACTION-53",
         "parentAction" : null,
         "user" : "USER-2",
         "workSourceName" : "admin",
         "startTime" : "2019-12-30T11:14:29.889Z",
         "failureMessageCode" : "exception.oracle.accessor.database.failed.connection",
         "title" : "DB_SYNC",
         "namespace" : null,
         "workSourcePrincipal" : "admin",
         "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
         "actionType" : "DB_SYNC"
      },
      {
         "parentAction" : null,
         "user" : "USER-2",
         "workSourceName" : "admin",
         "startTime" : "2019-12-30T11:14:20.759Z",
         "failureMessageCode" : "exception.oracle.accessor.database.failed.connection",
         "title" : "DB_SYNC",
         "namespace" : null,
         "workSourcePrincipal" : "admin",
         "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
         "actionType" : "DB_SYNC",
         "originIp" : "172.16.124.26",
         "details" : "Run SnapSync for database \"marina\".",
         "report" : null,
         "state" : "FAILED",
         "type" : "Action",
         "workSource" : "WEBSERVICE",
         "endTime" : "2019-12-30T11:14:22.925Z",
         "failureAction" : "Make sure that the username provided has access rights to system views, and that the host server can be reached.",
         "failureDescription" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n ",
         "reference" : "ACTION-52"
      }
   ],
   "status" : "OK",
   "total" : 3,
   "type" : "ListResult",
   "action" : null,
   "job" : null,
   "overflow" : false
}
