{
   "overflow" : false,
   "job" : null,
   "action" : null,
   "total" : 8,
   "result" : [
      {
         "type" : "Fault",
         "dateDiagnosed" : "2018-01-23T11:30:03.704Z",
         "severity" : "CRITICAL",
         "targetObjectType" : "OracleDatabaseContainer",
         "resolutionComments" : null,
         "bundleID" : "fault.policy.dsource.policy.connect.failed",
         "dateResolved" : null,
         "description" : "Unable to connect to database \"marina\" via JDBC. The database or host may be down. Connection error: Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n .",
         "targetName" : "Sources/marina",
         "namespace" : null,
         "status" : "ACTIVE",
         "reference" : "FAULT-23",
         "title" : "Unable to connect to remote database during dSource policy enforcement",
         "action" : "Make sure that the affected database is running and connectivity is available.",
         "response" : "dSource snapshot policy is disabled.",
         "target" : "ORACLE_DB_CONTAINER-1"
      },
      {
         "description" : "Unable to connect to database \"PDBX1\" via JDBC. The database or host may be down. Connection error: Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: Listener refused the connection with the following error:\nORA-12514, TNS:listener does not currently know of service requested in connect descriptor\n .",
         "dateResolved" : null,
         "bundleID" : "fault.policy.dsource.policy.connect.failed",
         "targetObjectType" : "OracleDatabaseContainer",
         "severity" : "CRITICAL",
         "resolutionComments" : null,
         "dateDiagnosed" : "2018-01-23T11:30:02.366Z",
         "type" : "Fault",
         "target" : "ORACLE_DB_CONTAINER-4",
         "response" : "dSource snapshot policy is disabled.",
         "action" : "Make sure that the affected database is running and connectivity is available.",
         "title" : "Unable to connect to remote database during dSource policy enforcement",
         "reference" : "FAULT-22",
         "status" : "ACTIVE",
         "targetName" : "Sources/PDBX1",
         "namespace" : null
      },
      {
         "status" : "RESOLVED",
         "reference" : "FAULT-21",
         "title" : "LogSync failed to connect to remote database",
         "action" : "Make sure the host provided is a valid host reachable by the Delphix Engine.",
         "response" : "LogSync will slow down and check periodically until the problem is resolved.",
         "target" : "ORACLE_DB_CONTAINER-3",
         "targetName" : "Sources/carmel",
         "namespace" : null,
         "targetObjectType" : "OracleDatabaseContainer",
         "resolutionComments" : "Fault no longer present.",
         "severity" : "CRITICAL",
         "bundleID" : "fault.oracle.linkedsource.connect.jdbc",
         "dateResolved" : "2018-01-20T01:24:46.409Z",
         "description" : "Cannot connect to database: Make sure that the database instance can be reached through at least one of the following connection strings: [jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=broken)(ADDRESS=(PROTOCOL=tcp)(HOST=10.43.8.174)(PORT=1521))(CONNECT_DATA=(UR=A)(SID=carmel))); ]",
         "type" : "Fault",
         "dateDiagnosed" : "2018-01-20T01:24:45.200Z"
      },
      {
         "targetName" : "Sources/carmel",
         "namespace" : null,
         "reference" : "FAULT-20",
         "status" : "ACTIVE",
         "target" : "ORACLE_TIMEFLOW-3",
         "response" : null,
         "action" : "Use the CLI TimeFlow Log Fetch command to retrieve the missing log. The log can only be retrieved from a non-ASM location.",
         "title" : "Cannot provision a database from a portion of TimeFlow",
         "type" : "Fault",
         "dateDiagnosed" : "2018-01-09T03:01:18.688Z",
         "dateResolved" : null,
         "bundleID" : "fault.oracle.linkedsource.notprovisionable.timeflow.failedlogs",
         "resolutionComments" : null,
         "severity" : "WARNING",
         "targetObjectType" : "OracleTimeflow",
         "description" : "Database \"carmel\" TimeFlow \"default\" is missing log sequence 1.1072 because LogSync failed to fetch it more than 3 times."
      },
      {
         "description" : "Cannot connect to database: Make sure that the database instance can be reached through at least one of the following connection strings: [jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=broken)(ADDRESS=(PROTOCOL=tcp)(HOST=10.43.8.174)(PORT=1521))(CONNECT_DATA=(UR=A)(SID=carmel))); ]",
         "resolutionComments" : "Fault no longer present.",
         "targetObjectType" : "OracleDatabaseContainer",
         "severity" : "CRITICAL",
         "bundleID" : "fault.oracle.linkedsource.connect.jdbc",
         "dateResolved" : "2018-01-09T03:06:17.854Z",
         "dateDiagnosed" : "2018-01-09T03:01:09.623Z",
         "type" : "Fault",
         "title" : "LogSync failed to connect to remote database",
         "action" : "Make sure the host provided is a valid host reachable by the Delphix Engine.",
         "response" : "LogSync will slow down and check periodically until the problem is resolved.",
         "target" : "ORACLE_DB_CONTAINER-3",
         "status" : "RESOLVED",
         "reference" : "FAULT-19",
         "targetName" : "Sources/carmel",
         "namespace" : null
      },
      {
         "namespace" : null,
         "targetName" : "test/sdd",
         "status" : "ACTIVE",
         "reference" : "FAULT-18",
         "title" : "Unable to connect to remote database during virtual database policy enforcement",
         "action" : "Start the affected database and make sure connectivity is available.",
         "response" : "Virtual database snapshot policy is disabled.",
         "target" : "ORACLE_DB_CONTAINER-37",
         "type" : "Fault",
         "dateDiagnosed" : "2017-12-28T11:30:01.143Z",
         "targetObjectType" : "OracleDatabaseContainer",
         "resolutionComments" : null,
         "severity" : "WARNING",
         "bundleID" : "fault.policy.vdb.policy.connect.failed",
         "dateResolved" : null,
         "description" : "Unable to connect to the database \"sdd\". The database or host may be down. Connection error: Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: Listener refused the connection with the following error:\nORA-12514, TNS:listener does not currently know of service requested in connect descriptor\n ."
      },
      {
         "type" : "Fault",
         "dateDiagnosed" : "2017-12-28T11:30:00.434Z",
         "severity" : "WARNING",
         "targetObjectType" : "OracleDatabaseContainer",
         "resolutionComments" : null,
         "bundleID" : "fault.policy.vdb.policy.connect.failed",
         "dateResolved" : null,
         "description" : "Unable to connect to the database \"Vtes_X6F\". The database or host may be down. Connection error: Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: Listener refused the connection with the following error:\nORA-12514, TNS:listener does not currently know of service requested in connect descriptor\n .",
         "targetName" : "Sources/Vtes_X6F",
         "namespace" : null,
         "status" : "ACTIVE",
         "reference" : "FAULT-17",
         "title" : "Unable to connect to remote database during virtual database policy enforcement",
         "action" : "Start the affected database and make sure connectivity is available.",
         "response" : "Virtual database snapshot policy is disabled.",
         "target" : "ORACLE_DB_CONTAINER-33"
      },
      {
         "bundleID" : "fault.genericcontainer.hook.operations.failed",
         "resolutionComments" : "Object deleted.",
         "severity" : "WARNING",
         "targetObjectType" : "OracleDatabaseContainer",
         "dateResolved" : "2017-12-27T16:09:18.496Z",
         "description" : "Either the Hook operations could not be run due to issues with the target environment or an operation exited with a non-zero exit status.",
         "type" : "Fault",
         "dateDiagnosed" : "2017-12-27T16:04:19.184Z",
         "status" : "RESOLVED",
         "reference" : "FAULT-16",
         "action" : "Inspect the Delphix Engine's event viewer for more information about the failure.",
         "title" : "Hook operations failed to complete successfully",
         "target" : "ORACLE_DB_CONTAINER-36",
         "response" : null,
         "targetName" : "test/sdd",
         "namespace" : null
      }
   ],
   "type" : "ListResult",
   "status" : "OK"
}
